type ErrorCode = 'NOT_AUTHENTICATED' | 'AUTH_INVALID_CREDENTIALS' | 'INSUFFICIENT_PERMISSIONS'
    | 'ACCOUNT_NOT_ACTIVE' | 'SUBSCRIPTION_EXPIRED'
    | 'SCHEDULE_CONFLICT' | 'INVALID_TIME_RANGE'
    | 'BAD_REQUEST' | 'ALREADY_EXISTS' | 'NOT_FOUND' | 'TOO_MANY_REQUESTS'
    | 'DATABASE_ERROR' | 'INTERNAL_SERVER_ERROR';